### PR TITLE
Fix captive portal crash

### PR DESCRIPTION
**Pull request by redmushie**
WIP

### CODE REVIEW

**Comment by hhvrc** [comment]
Looking good, what kinda results u getting? 🤔

**Comment by redmushie** [comment]
@hhvrc I posted an update 4 hours ago in #80 💀

**Comment by LucHeart** [comment]
The logs you added are not shown anywhere. Are we sure this is running?

**Comment by LucHeart** [comment]
Hm okay, it seems to run in build-frontend...

**Comment by redmushie** [comment]
@LucHeart build-filesystem*.
not to mention I screenshotted it in #80 too.
deleting this now

**Pull request closed without merging**
